matrix:
  VERSION:
    - "1.12.1"

build:
  clone:
    image: armhfbuild/buildpack-deps:jessie-scm
    commands:

  binary:
    image: armhfbuild/docker:1.12-dind
    privileged: true
    commands:
      - apk add --update bash git make
      # FIXME Replace this hack when there is a real Docker build plugin
      - docker daemon -s aufs -g /drone/docker &
      - sleep 2
      - docker daemon -s overlay -g /drone/docker &
      - sleep 2
      - rm upstream -fR && git clone --single-branch --branch v$$VERSION https://github.com/docker/docker upstream
      - cd upstream
      - make binary
      - cd bundles/$$VERSION
      - mkdir docker
      - cp binary-client/docker docker/
      - cd binary-daemon && cp docker-containerd docker-containerd-ctr docker-containerd-shim dockerd docker-proxy docker-runc ../docker/ && cd ..
      - tar czf docker-$$VERSION.tgz docker

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files: upstream/bundles/$$VERSION/docker-$$VERSION.tgz*
    checksum: sha256

cache:
  mount:
    - /drone/docker

notify:
  downstream:
    repositories:
      - armhf-docker-library/docker
    token: $$DRONE_API_TOKEN
    fork: true
    when:
      event: push
      success: true

  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
